// <auto-generated />
namespace Main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Edittypedonvimuadvb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edittypedonvimuadvb));
        
        string IMigrationMetadata.Id
        {
            get { return "201805041715333_Edit type donvimua+dvb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
